version: "3.8"
services:
  postgres:
    image: postgres:16.1
    # volumes:
    #   - ./postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak-clustered-1:
    image: "ivanfranchin/keycloak-clustered:latest"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_SCHEMA=myschema
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      - JGROUPS_DISCOVERY_EXTERNAL_IP=keycloak-clustered-1

  keycloak-clustered-2:
    image: "ivanfranchin/keycloak-clustered:latest"
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_SCHEMA=myschema
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      - JGROUPS_DISCOVERY_EXTERNAL_IP=keycloak-clustered-2